[package]
name = "sum-addon"
version = "0.1.0"
edition = "2021"
description = "Native addon to sum Uint16Array for fast expression analyze"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2"
napi-derive = "2"

[build-dependencies]
napi-build = "2"
